#ifndef DISCOUNT_WDF_DRIVERSPECS_H
#define DISCOUNT_WDF_DRIVERSPECS_H

/* WDK SAL is compile-time metadata only. */
#define _Dispatch_type_(x)
#define __drv_dispatchType(x)
#define __drv_functionClass(x)
#define __drv_sameIRQL
#define __drv_maxIRQL(x)
#define __drv_minFunctionIRQL(x)
#define __drv_requiresIRQL(x)
#define __drv_setsIRQL(x)
#define __drv_aliasesMem
#define __drv_out_deref(x)
#define __drv_in_deref
#define __drv_when(x,y)
#define __drv_formatString
#define __drv_strictTypeMatch
#define __drv_clearDoInit(x)
#define __drv_allocatesMem(x)
#define __drv_freesMem(x)
#define __drv_valueIs(x)
#define __drv_unit(x)
#define __drv_arg(x)
#define __drv_preferredFunction(x,y)
#define __drv_impl(x)
#define __drv_reportError(x)
#define __analysis_assume(x) ((void)0)
#define _Analysis_assume_(x) ((void)0)
#define _Analysis_mode_(x)
#define _Must_inspect_result_
#define _When_(x,y)
#define _Success_(x)
#define _At_(x,y)
#define _Post_same_lock_(x)
#define _Requires_lock_held_(x)
#define _Requires_lock_not_held_(x)
#define _Acquires_lock_(x)
#define _Releases_lock_(x)
#define _IRQL_requires_same_
#define _IRQL_requires_max_(x)
#define _IRQL_requires_min_(x)
#define _IRQL_requires_(x)
#define _IRQL_raises_(x)
#define _IRQL_saves_global_(x,y,z)
#define _IRQL_restores_global_(x,y,z)
#define _Function_ignore_lock_checking_(x)
#define _Post_ptr_invalid_
#define _Post_maybenull_
#define _Post_z_
#define _Pre_z_
#define _In_z_
#define _In_reads_(x)
#define _In_reads_bytes_(x)
#define _In_reads_bytes_opt_(x)
#define _Out_writes_(x)
#define _Out_writes_all_(x)
#define _Out_writes_bytes_(x)
#define _Out_writes_bytes_to_(x,y,z)
#define _Outptr_result_maybenull_
#define _Outptr_result_z_
#define _Ret_maybenull_
#define _Ret_notnull_
#define _Post_invalid_
#define _Post_satisfies_(x)
#define _Pre_satisfies_(x)
#define _Function_class_(x)
#define _Group_annotate_(x)
#define _Field_size_(x)
#define _Field_size_bytes_(x)
#define _Field_size_bytes_part_(x,y)
#define _Field_size_bytes_part_opt_(x,y)
#define _Field_size_full_(x)
#define _Field_size_full_opt_(x)
#define _Null_terminated_
#define _Notliteral_
#define _Enum_is_bitflag_
#define _Return_type_success_(x)
#define __user_code
#define __drv_aliasesMem

#endif
