#ifndef VERSION_H
#define VERSION_H

#define DISCOUNT_NAME "discouNT"
#define DISCOUNT_VERSION "0.0.4"
#define DISCOUNT_WIN32_MAJOR 10
#define DISCOUNT_WIN32_MINOR 0
#define DISCOUNT_WIN32_BUILD 19041

#endif
