#ifndef DISCOUNT_REGEDIT_API_H
#define DISCOUNT_REGEDIT_API_H
#include <windows.h>
#include <commctrl.h>
#include <commdlg.h>
#include <aclapi.h>
#include <objbase.h>
#include <objsel.h>
typedef void *IAutoComplete;
typedef void *IEnumString;
extern GUID IID_IEnumString;
extern GUID IID_IAutoComplete;
extern GUID CLSID_AutoComplete;
extern GUID GUID_NULL;
typedef struct { NMHDR hdr; int iItem; int iSubItem; UINT uNewState,uOldState; DWORD uChanged; POINT pt; LPARAM lParam; } NMLISTVIEW;
typedef NMLISTVIEW *LPNMLISTVIEW;
typedef struct { NMHDR hdr; LVITEMW item; } NMLVDISPINFO;
typedef NMLVDISPINFO *LPNMLVDISPINFO;
typedef struct { NMHDR hdr; TVITEMW item; } NMTVDISPINFO;
typedef NMTVDISPINFO *LPNMTVDISPINFO;
typedef OPENFILENAMEW OPENFILENAME;
typedef OFNOTIFYW OFNOTIFY;
typedef PRINTDLGW PRINTDLG;
typedef const WCHAR *LPCWCH;
typedef const char *PCCH;
typedef struct { UINT flags; LPCWSTR psz; } LVFINDINFOW;
typedef LVFINDINFOW LVFINDINFO;
typedef HDITEMW HDITEM;
typedef LOGFONTW LOGFONT;
typedef TEXTMETRICW TEXTMETRIC;
typedef CREATESTRUCTW CREATESTRUCT;
typedef struct { SHORT x, y; } POINTS, *LPPOINTS;
typedef enum { InterfaceTypeUndefined = 0, Internal = 1, Isa = 2, Eisa = 3, MicroChannel = 4, TurboChannel = 5, PCIBus = 6, PCMCIABus = 8, Generic = 0x80, PNPISABus = 14, PNPBus = 16, PCIeBus = 23 } INTERFACE_TYPE;
#define VMEBus 9
#define NuBus 10
#define CBus 11
#define MPIBus 12
#define MPSABus 13
#define ProcessorInternal 15
#define InternalPowerBus 17
#define LPSTR_TEXTCALLBACKW ((LPWSTR)(intptr_t)-1)
#define LVNI_FOCUSED 1
#define LVNI_SELECTED 2
#define LVFI_STRING 2
#define LVM_GETEDITCONTROL (0x1000+24)
#define LVM_SETCOLUMNWIDTH (0x1000+30)
#define LVM_EDITLABELW (0x1000+118)
#define LVM_ENSUREVISIBLE (0x1000+19)
#define LVM_FINDITEMW (0x1000+83)
#define LVM_GETCOLUMNWIDTH (0x1000+29)
#define LVM_GETNEXTITEM (0x1000+12)
#define LVM_SETITEMSTATE (0x1000+43)
#define LVIS_FOCUSED 1
#define LVN_BEGINLABELEDIT ((UINT)-175)
#define LVN_ENDLABELEDIT ((UINT)-176)
#define LVN_COLUMNCLICK ((UINT)-108)
#define LVN_GETDISPINFO ((UINT)-177)
#define TVI_ROOT ((HTREEITEM)(intptr_t)-0x10000)
#define TVI_LAST ((HTREEITEM)(intptr_t)-0xFFFE)
#define TVE_COLLAPSE 1
#define TVIS_EXPANDEDONCE 0x0040
#define TVSIL_NORMAL 0
#define TVS_HASBUTTONS 1
#define TVS_HASLINES 2
#define TVS_LINESATROOT 4
#define TVS_SHOWSELALWAYS 0x20
#define TVS_EDITLABELS 8
#define TVM_GETEDITCONTROL (0x1100+15)
#define TVM_SORTCHILDREN (0x1100+19)
#define TVM_GETNEXTITEM (0x1100+10)
#define TVM_INSERTITEMW (0x1100+50)
#define TVM_DELETEITEM (0x1100+1)
#define TVM_SELECTITEM (0x1100+11)
#define TVM_EXPAND (0x1100+2)
#define TVM_GETITEMW (0x1100+62)
#define TVM_SETITEMW (0x1100+63)
#define TVM_GETITEMSTATE (0x1100+39)
#define TVM_EDITLABELW (0x1100+65)
#define TVM_ENSUREVISIBLE (0x1100+20)
#define TVM_GETEDITCONTROL (0x1100+15)
#define TVM_GETIMAGELIST (0x1100+8)
#define TVM_SETIMAGELIST (0x1100+9)
#define TVM_HITTEST (0x1100+17)
#define TVGN_ROOT 0
#define TVGN_NEXT 1
#define TVGN_PARENT 3
#define TVGN_CHILD 4
#define TVHT_ONITEM 0x46
#define WC_TREEVIEWW L"SysTreeView32"
#define WC_LISTVIEWW L"SysListView32"
#define WC_TREEVIEW WC_TREEVIEWW
#define WC_LISTVIEW WC_LISTVIEWW
#define BS_ICON 0x40
#define BS_CENTER 0x300
#define BS_VCENTER 0x0C00
#define BS_FLAT 0x8000
#define BM_SETIMAGE 0x00F7
#define DEFAULT_GUI_FONT 17
#define IDC_SIZEWE ((LPCWSTR)32644)
#define TPM_RIGHTBUTTON 2
#define NM_RETURN ((UINT)-4)
#define NM_SETFOCUS ((UINT)-7)
#define SM_CYEDGE 45
#define SWP_NOCOPYBITS 0x0100
#define RDW_NOCHILDREN 0x0040
#define DCX_CACHE 2
#define PATINVERT 0x005A0049
#define HDM_SETITEMW (0x1200+12)
#define KEY_ENUMERATE_SUB_KEYS 8
#define KEY_EXECUTE 0x20019
#define KEY_NOTIFY 0x0010
#define KEY_CREATE_LINK 0x0020
#define READ_CONTROL 0x00020000
#define WRITE_DAC 0x00040000
#define WRITE_OWNER 0x00080000
#define LHND 0x0042
#define WHEEL_DELTA 120
#define WM_NCDESTROY 0x0082
#define WM_SYSCOLORCHANGE 0x0015
#define VK_BACK 8
#define VK_DELETE 46
#define VK_INSERT 45
#define VK_LEFT 37
#define VK_RIGHT 39
#define VK_MENU 18
#define LANG_HEBREW 13
#define SUBLANG_DEFAULT 1
#define LAYOUT_RTL 1
#define SPI_GETWHEELSCROLLLINES 104
#define REG_OPENED_EXISTING_KEY 2
#define REG_FORCE_RESTORE 8
#define SE_BACKUP_NAME L"SeBackupPrivilege"
#define SE_RESTORE_NAME L"SeRestorePrivilege"
#define PD_USEDEVMODECOPIESANDCOLLATE 0x40000
#define SI_EDIT_ALL 0x000F
#define DELETE 0x00010000
#define ERROR_SUCCESS 0
#define ERROR_INVALID_FUNCTION 1
#define ERROR_INVALID_PARAMETER 87
#define ERROR_NOT_ENOUGH_MEMORY 8
#define ERROR_NO_MORE_ITEMS 259
#define ERROR_CANCELLED 1223
#define ERROR_NOT_ALL_ASSIGNED 1300
#define E_NOINTERFACE ((HRESULT)0x80004002L)
#define E_OUTOFMEMORY ((HRESULT)0x8007000EL)
#define ERANGE 34
#define EN_CHANGE 0x0300
#define EN_UPDATE 0x0400
#define _MAX_PATH 260
#define _O_BINARY 0x8000
#define GMEM_MOVEABLE 0x0002
#define GMEM_SHARE 0x0020
#define GHND (GMEM_MOVEABLE | GMEM_ZEROINIT)
#define WS_EX_WINDOWEDGE 0x00000100
#define IDC_IBEAM ((LPCWSTR)32513)
#define IDC_WAIT ((LPCWSTR)32514)
#define ICC_WIN95_CLASSES 0x000000FF
#define HDF_SORTUP 0x0400
#define HDF_SORTDOWN 0x0200
#define LVS_EDITLABELS 0x0200
#define LVS_NOSORTHEADER 0x8000
#define LVS_SHOWSELALWAYS 0x0008
#define MIIM_TYPE 0x00000010
#define MFT_STRING 0x00000000
#define MFS_DEFAULT 0x00001000
#define MFS_GRAYED 0x00000003
#define SI_EDIT_EFFECTIVE 0x00000080
#define SE_REGISTRY_KEY 0x0000000B
#define INHERIT_ONLY_ACE 0x00000008
#define IO_RESOURCE_ALTERNATIVE 0x00000008
#define IO_RESOURCE_PREFERRED 0x00000002
#define CmResourceShareDriverExclusive 2
#define CmResourceShareShared 3
#define CmResourceShareUndetermined 0
#define CmResourceTypeDeviceSpecific 5
#define CmResourceTypeDma 1
#define CmResourceTypeInterrupt 2
#define CmResourceTypeMemory 3
#define CmResourceTypePort 1
#undef CmResourceTypeDma
#define CmResourceTypeDma 4
#define REG_DWORD_BIG_ENDIAN 5
#define REG_LINK 6
#define FNERR_BUFFERTOOSMALL 0x3003
#define FNERR_INVALIDFILENAME 0x3002
#define FNERR_SUBCLASSFAILURE 0x3001
#define FORMAT_MESSAGE_IGNORE_INSERTS 0x00000200
#define CDERR_DIALOGFAILURE 0xFFFF
#define CDERR_FINDRESFAILURE 0x0006
#define CDERR_NOHINSTANCE 0x0004
#define CDERR_INITIALIZATION 0x0002
#define CDERR_NOHOOK 0x0009
#define CDERR_LOCKRESFAILURE 0x0008
#define CDERR_NOTEMPLATE 0x0007
#define CDERR_LOADRESFAILURE 0x0000
#define CDERR_STRUCTSIZE 0x0001
#define CDERR_LOADSTRFAILURE 0x0005
#define CDERR_MEMALLOCFAILURE 0x000B
#define CDERR_MEMLOCKFAILURE 0x000A
#define CDN_FILEOK ((UINT)-601)
#define CF_UNICODETEXT 13
#define ANSI_FIXED_FONT 11
#define COLOR_WINDOWTEXT 8
#define COLOR_HIGHLIGHT 13
#define COLOR_HIGHLIGHTTEXT 14
#define COLOR_3DFACE COLOR_BTNFACE
#define GMEM_ZEROINIT 0x0040
#define LPSTR_TEXTCALLBACK ((LPWSTR)(intptr_t)-1)
#define DECLSPEC_IMPORT
#define DWORDLONG uint64_t
#define MAKELANGID(p,s) ((WORD)(((s) << 10) | (p)))
#define HRESULT_FROM_WIN32(x) ((HRESULT)(x))
#define UlongToPtr(x) ((LPVOID)(ULONG_PTR)(x))
#define GENERIC_READ 0x80000000UL
#define GENERIC_WRITE 0x40000000UL
#define GENERIC_EXECUTE 0x20000000UL
#define GENERIC_ALL 0x10000000UL
#define ZERO_ACCESS 0
#define ERROR_INVALID_HANDLE 6
#define ERROR_NO_SYSTEM_RESOURCES 145
#define CM_RESOURCE_PORT_IO 0x0001
#define CM_RESOURCE_PORT_MEMORY 0x0000
#define CM_RESOURCE_INTERRUPT_LATCHED 0x0001
#define CM_RESOURCE_INTERRUPT_LEVEL_SENSITIVE 0x0000
#define CM_RESOURCE_MEMORY_READ_ONLY 0x0001
#define CM_RESOURCE_MEMORY_WRITE_ONLY 0x0002
#define CM_RESOURCE_MEMORY_READ_WRITE 0x0000
#define CM_RESOURCE_INTERRUPT_LEVEL_LATCHED_BITS 0x0001
#define CmResourceShareDeviceExclusive 1
#define S_FALSE ((HRESULT)1)
#define E_NOTIMPL ((HRESULT)0x80004001L)
#define ILC_COLOR32 0x0020
#define OPENFILENAME OPENFILENAMEW
#define PrintDlg PrintDlgW
#define GetOpenFileName GetOpenFileNameW
#define GetSaveFileName GetSaveFileNameW
#define RegOpenKey RegOpenKeyW
#define RegCreateKey RegCreateKeyW
#define RegDeleteValue RegDeleteValueW
#define RegSaveKey RegSaveKeyW
#define RegisterClassEx RegisterClassExW
#define GetWindowLongPtr GetWindowLongPtrW
#define SetWindowLongPtr SetWindowLongPtrW
#define SendMessage SendMessageW
#define CreateFontIndirect CreateFontIndirectW
#define LoadCursor LoadCursorW
#define GetTextMetrics GetTextMetricsW
#define CreateWindowEx CreateWindowExW
#define wsprintf wsprintfW
#define GUID_NULL ((GUID){0})
/* The ReactOS sources use the SDK's common-control convenience macros. */
#define ListView_InsertItem(h,p) ListView_InsertItemW((h),(p))
#define ListView_InsertColumn(h,i,p) ListView_InsertColumnW((h),(i),(p))
#define ListView_SetItemText(h,i,s,p) ListView_SetItemTextW((h),(i),(s),(p))
#define ListView_GetItemText(h,i,s,p,n) ListView_GetItemTextW((h),(i),(s),(p),(n))
#define ListView_GetItemCount(h) ((int)SendMessageW((h),LVM_GETITEMCOUNT,0,0))
#define ListView_GetSelectedCount(h) ((int)SendMessageW((h),LVM_GETSELECTEDCOUNT,0,0))
#define ListView_GetHeader(h) ((HWND)SendMessageW((h),LVM_GETHEADER,0,0))
#define ListView_DeleteAllItems(h) ((BOOL)SendMessageW((h),LVM_DELETEALLITEMS,0,0))
#define ListView_SetExtendedListViewStyle(h,s) ((DWORD)SendMessageW((h),LVM_SETEXTENDEDLISTVIEWSTYLE,0,(LPARAM)(s)))
#define ListView_SetColumnWidth(h,i,c) ((BOOL)SendMessageW((h),LVM_SETCOLUMNWIDTH,(WPARAM)(i),(LPARAM)(c)))
#define TreeView_GetParent(h,i) ((HTREEITEM)SendMessageW((h),TVM_GETNEXTITEM,TVGN_PARENT,(LPARAM)(i)))
#define TreeView_GetSelection(h) ((HTREEITEM)SendMessageW((h),TVM_GETNEXTITEM,TVGN_CARET,0))
#define TreeView_GetRoot(h) ((HTREEITEM)SendMessageW((h),TVM_GETNEXTITEM,TVGN_ROOT,0))
#define TreeView_GetChild(h,i) ((HTREEITEM)SendMessageW((h),TVM_GETNEXTITEM,TVGN_CHILD,(LPARAM)(i)))
#define TreeView_GetNextSibling(h,i) ((HTREEITEM)SendMessageW((h),TVM_GETNEXTITEM,TVGN_NEXT,(LPARAM)(i)))
#define TreeView_InsertItem(h,p) ((HTREEITEM)SendMessageW((h),TVM_INSERTITEMW,0,(LPARAM)(p)))
#define TreeView_DeleteItem(h,i) ((BOOL)SendMessageW((h),TVM_DELETEITEM,0,(LPARAM)(i)))
#define TreeView_SelectItem(h,i) ((BOOL)SendMessageW((h),TVM_SELECTITEM,TVGN_CARET,(LPARAM)(i)))
#define TreeView_Expand(h,i,c) ((BOOL)SendMessageW((h),TVM_EXPAND,(c),(LPARAM)(i)))
#define TreeView_GetItem(h,p) ((BOOL)SendMessageW((h),TVM_GETITEMW,0,(LPARAM)(p)))
#define TreeView_SetItem(h,p) ((BOOL)SendMessageW((h),TVM_SETITEMW,0,(LPARAM)(p)))
#define TreeView_GetItemState(h,i,m) ((UINT)SendMessageW((h),TVM_GETITEMSTATE,(WPARAM)(i),(LPARAM)(m)))
#define Header_GetItem(h,i,p) ((BOOL)SendMessageW((h),HDM_GETITEMW,(WPARAM)(i),(LPARAM)(p)))
#define Header_SetItem(h,i,p) ((BOOL)SendMessageW((h),HDM_SETITEMW,(WPARAM)(i),(LPARAM)(p)))
#define IAutoComplete_Init(p,a,b,c,d) E_NOTIMPL
#define IAutoComplete_Release(p) ((ULONG)0)
#define AppendMenu AppendMenuW
#define InsertMenuItem InsertMenuItemW
#define SetMenuItemInfo SetMenuItemInfoW
#define GetMenuItemInfo GetMenuItemInfoW
#define GetModuleHandle GetModuleHandleW
#define GetWindowTextLength GetWindowTextLengthW
#define GetObject GetObjectW
#define GetFocus() ((HWND)0)
#define GetUpdateRect(h,r,e) ((BOOL)0)
#define MoveMemory memmove
#define _snwprintf swprintf
#define _vsnwprintf vswprintf
#define StringCbVPrintfW(...) S_OK
#define StringCchVPrintfW(...) S_OK
#define ListView_EditLabel(h,i) ((HWND)SendMessageW((h),LVM_EDITLABELW,(WPARAM)(i),0))
#define ListView_EnsureVisible(h,i,f) ((BOOL)SendMessageW((h),LVM_ENSUREVISIBLE,(WPARAM)(i),(LPARAM)(f)))
#define ListView_FindItem(h,i,p) ((int)SendMessageW((h),LVM_FINDITEMW,(WPARAM)(i),(LPARAM)(p)))
#define ListView_GetColumnWidth(h,i) ((int)SendMessageW((h),LVM_GETCOLUMNWIDTH,(WPARAM)(i),0))
#define ListView_GetItem(h,p) ((BOOL)SendMessageW((h),LVM_GETITEMW,0,(LPARAM)(p)))
#define ListView_GetNextItem(h,i,f) ((int)SendMessageW((h),LVM_GETNEXTITEM,(WPARAM)(i),(LPARAM)(f)))
#define ListView_SetItemState(h,i,s,m) ((BOOL)SendMessageW((h),LVM_SETITEMSTATE,(WPARAM)(i),(LPARAM)&(LVITEMW){LVIF_STATE,(i),0,(s),(m),0,0,0,0,0}))
#define ListView_GetItemState(h,i,m) ((UINT)SendMessageW((h),LVM_GETITEMSTATE,(WPARAM)(i),(LPARAM)(m)))
#define ListView_SortItems(h,cmp,l) ((BOOL)SendMessageW((h),LVM_SORTITEMS,0,(LPARAM)(l)))
#define ListView_SetImageList(h,l,t) ((HIMAGELIST)SendMessageW((h),LVM_SETIMAGELIST,(WPARAM)(t),(LPARAM)(l)))
#define TreeView_EditLabel(h,i) ((HWND)SendMessageW((h),TVM_EDITLABELW,0,(LPARAM)(i)))
#define TreeView_EnsureVisible(h,i) ((BOOL)SendMessageW((h),TVM_ENSUREVISIBLE,0,(LPARAM)(i)))
#define TreeView_GetEditControl(h) ((HWND)SendMessageW((h),TVM_GETEDITCONTROL,0,0))
#define TreeView_GetImageList(h,t) ((HIMAGELIST)SendMessageW((h),TVM_GETIMAGELIST,(WPARAM)(t),0))
#define TreeView_SetImageList(h,l,t) ((HIMAGELIST)SendMessageW((h),TVM_SETIMAGELIST,(WPARAM)(t),(LPARAM)(l)))
#define TreeView_HitTest(h,p) ((HTREEITEM)SendMessageW((h),TVM_HITTEST,0,(LPARAM)(p)))
#define TreeView_Select(h,i,c) ((HTREEITEM)SendMessageW((h),TVM_SELECTITEM,(WPARAM)(c),(LPARAM)(i)))
#endif
