#ifndef DISCOUNT_SHLOBJ_H
#define DISCOUNT_SHLOBJ_H
#include "shobjidl.h"
#define CSIDL_DESKTOP 0
#define CSIDL_CONTROLS 3
#define CSIDL_STARTMENU 11
#define CSIDL_COMMON_STARTMENU 22
#define KF_FLAG_CREATE 0x8000
extern const GUID FOLDERID_Desktop, FOLDERID_PublicDesktop;
UINT WINAPI ILGetSize(LPCITEMIDLIST pidl);
LPITEMIDLIST WINAPI ILClone(LPCITEMIDLIST pidl);
LPITEMIDLIST WINAPI ILCloneFirst(LPCITEMIDLIST pidl);
LPITEMIDLIST WINAPI ILCombine(LPCITEMIDLIST first,LPCITEMIDLIST second);
LPCITEMIDLIST WINAPI ILGetNext(LPCITEMIDLIST pidl);
BOOL WINAPI ILIsEmpty(LPCITEMIDLIST pidl);
BOOL WINAPI ILIsEqual(LPCITEMIDLIST first,LPCITEMIDLIST second);
BOOL WINAPI ILIsParent(LPCITEMIDLIST parent,LPCITEMIDLIST child,BOOL immediate);
LPITEMIDLIST WINAPI ILFindChild(LPCITEMIDLIST parent,LPCITEMIDLIST child);
LPITEMIDLIST WINAPI ILCreateFromPathW(LPCWSTR path);
void WINAPI ILFree(LPITEMIDLIST pidl);
HRESULT WINAPI SHGetDesktopFolder(IShellFolder **folder);
HRESULT WINAPI SHGetSpecialFolderLocation(HWND hwnd,int csidl,LPITEMIDLIST *pidl);
HRESULT WINAPI SHGetKnownFolderPath(REFGUID folder,DWORD flags,HANDLE token,LPWSTR *path);
BOOL WINAPI SHGetPathFromIDListW(LPCITEMIDLIST pidl,LPWSTR path);
HRESULT WINAPI SHBindToParent(LPCITEMIDLIST pidl,REFIID iid,void **parent,LPCITEMIDLIST *child);
HRESULT WINAPI SHGetIDListFromObject(IUnknown *object,LPITEMIDLIST *pidl);
HRESULT WINAPI StrRetToStrW(STRRET *str,LPCITEMIDLIST pidl,LPWSTR *text);
#endif
